*** Variables ***
${URL} =  https://test.skatteinformation.se/
${USERNAME_USER} =  infotiv-user
${USERNAME_EDITOR} =  infotiv-editor
${PASSWORD} =  slimy-very-decorate-transit
${RESET_USERNAME} =  infotiv-user-reset
${RESET_PASSWORD} =  slimy-very-decorate-transit
${RESET_EMAIL} =  softvarutestare@gmail.com
${RESET_EMAIL_PASSWORD} =  slimy-very-decorate-transit
